description
 Program     : welcome.scl
 Author      : J M Garrido, November 20, 2019.
 Description : Display welcome message on the screen
    and the value of variable x.
 Modified by Ethan Butler March 24, 2022
 */
import "scl.h"
implementations
function main return type integer is
variables
    define x of type double   // a variable declaration
begin
    display "Welcome"
    set x = 45	// assigns a value to variable x
    display "x:", x
    exit                      // execution terminates OK
endfun main
